# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andre/Documents/Coding/ADA_Proyecto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andre/Documents/Coding/ADA_Proyecto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andre/Documents/Coding/ADA_Proyecto/CMakeFiles /home/andre/Documents/Coding/ADA_Proyecto//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andre/Documents/Coding/ADA_Proyecto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named adaBD

# Build rule for target.
adaBD: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 adaBD
.PHONY : adaBD

# fast build rule for target.
adaBD/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adaBD.dir/build.make CMakeFiles/adaBD.dir/build
.PHONY : adaBD/fast

# target to build an object file
src/btree.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adaBD.dir/build.make CMakeFiles/adaBD.dir/src/btree.o
.PHONY : src/btree.o

# target to preprocess a source file
src/btree.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adaBD.dir/build.make CMakeFiles/adaBD.dir/src/btree.i
.PHONY : src/btree.i

# target to generate assembly for a file
src/btree.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adaBD.dir/build.make CMakeFiles/adaBD.dir/src/btree.s
.PHONY : src/btree.s

# target to build an object file
src/cuckohashing.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adaBD.dir/build.make CMakeFiles/adaBD.dir/src/cuckohashing.o
.PHONY : src/cuckohashing.o

# target to preprocess a source file
src/cuckohashing.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adaBD.dir/build.make CMakeFiles/adaBD.dir/src/cuckohashing.i
.PHONY : src/cuckohashing.i

# target to generate assembly for a file
src/cuckohashing.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adaBD.dir/build.make CMakeFiles/adaBD.dir/src/cuckohashing.s
.PHONY : src/cuckohashing.s

# target to build an object file
src/firstload.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adaBD.dir/build.make CMakeFiles/adaBD.dir/src/firstload.o
.PHONY : src/firstload.o

# target to preprocess a source file
src/firstload.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adaBD.dir/build.make CMakeFiles/adaBD.dir/src/firstload.i
.PHONY : src/firstload.i

# target to generate assembly for a file
src/firstload.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/adaBD.dir/build.make CMakeFiles/adaBD.dir/src/firstload.s
.PHONY : src/firstload.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... adaBD"
	@echo "... src/btree.o"
	@echo "... src/btree.i"
	@echo "... src/btree.s"
	@echo "... src/cuckohashing.o"
	@echo "... src/cuckohashing.i"
	@echo "... src/cuckohashing.s"
	@echo "... src/firstload.o"
	@echo "... src/firstload.i"
	@echo "... src/firstload.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

